"""final correction

Revision ID: 48af8e613051
Revises: efdd99919772
Create Date: 2024-03-21 22:04:53.424174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48af8e613051'
down_revision: Union[str, None] = 'efdd99919772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_ticket', 'ticket_type')
    op.drop_column('user', 'is_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_verified', sa.BOOLEAN(), nullable=True))
    op.add_column('event_ticket', sa.Column('ticket_type', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
